import type {
  LocalStock,
  MarketId,
  MarketIndex,
  Sukuk,
  InvestmentFund,
} from "@/types/markets";

// ── Market Indices ──

export const MARKET_INDICES: MarketIndex[] = [
  {
    id: "msm30",
    marketId: "msm",
    nameKey: "markets.indices.msm30",
    symbol: "MSM30",
    value: 4782.34,
    change: 23.17,
    changePercent: 0.49,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "tasi",
    marketId: "tadawul",
    nameKey: "markets.indices.tasi",
    symbol: "TASI",
    value: 11834.56,
    change: -45.23,
    changePercent: -0.38,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "dfm",
    marketId: "dfm",
    nameKey: "markets.indices.dfm",
    symbol: "DFMGI",
    value: 4156.78,
    change: 12.45,
    changePercent: 0.3,
    lastUpdated: new Date().toISOString(),
  },
];

// ── Muscat Securities Market (MSM) ──

export const MSM_STOCKS: LocalStock[] = [
  {
    symbol: "BKMB",
    nameAr: "بنك مسقط",
    nameEn: "Bank Muscat",
    marketId: "msm",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 0.452,
    change: 0.008,
    changePercent: 1.8,
    high: 0.458,
    low: 0.445,
    volume: 1250000,
    marketCap: 2800000000,
    currency: "OMR",
    halalStatus: "suspicious",
    halalReason: "halalReasons.conventionalBanking",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "OTEL",
    nameAr: "عمانتل",
    nameEn: "Omantel",
    marketId: "msm",
    sector: "Telecom",
    sectorAr: "اتصالات",
    price: 0.714,
    change: -0.003,
    changePercent: -0.42,
    high: 0.72,
    low: 0.71,
    volume: 890000,
    marketCap: 5400000000,
    currency: "OMR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "ORES",
    nameAr: "النهضة للخدمات",
    nameEn: "Renaissance Services",
    marketId: "msm",
    sector: "Services",
    sectorAr: "خدمات",
    price: 0.385,
    change: 0.012,
    changePercent: 3.21,
    high: 0.39,
    low: 0.375,
    volume: 560000,
    marketCap: 670000000,
    currency: "OMR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "OCBI",
    nameAr: "بنك عمان العربي",
    nameEn: "Oman Arab Bank",
    marketId: "msm",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 0.178,
    change: -0.002,
    changePercent: -1.11,
    high: 0.182,
    low: 0.176,
    volume: 420000,
    marketCap: 530000000,
    currency: "OMR",
    halalStatus: "non_compliant",
    halalReason: "halalReasons.interestBased",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "OGCD",
    nameAr: "الغاز المتكامل",
    nameEn: "OQ Gas Networks",
    marketId: "msm",
    sector: "Energy",
    sectorAr: "طاقة",
    price: 0.132,
    change: 0.004,
    changePercent: 3.13,
    high: 0.135,
    low: 0.129,
    volume: 780000,
    marketCap: 920000000,
    currency: "OMR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "OMNI",
    nameAr: "عمان للتأمين",
    nameEn: "Oman Insurance",
    marketId: "msm",
    sector: "Insurance",
    sectorAr: "تأمين",
    price: 0.296,
    change: 0.001,
    changePercent: 0.34,
    high: 0.3,
    low: 0.292,
    volume: 150000,
    marketCap: 310000000,
    currency: "OMR",
    halalStatus: "suspicious",
    halalReason: "halalReasons.conventionalInsurance",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "OFCI",
    nameAr: "الأنوار القابضة",
    nameEn: "Al Anwar Holding",
    marketId: "msm",
    sector: "Investment",
    sectorAr: "استثمار",
    price: 0.215,
    change: 0.006,
    changePercent: 2.87,
    high: 0.218,
    low: 0.21,
    volume: 340000,
    marketCap: 480000000,
    currency: "OMR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "MRSA",
    nameAr: "أكوا باور صلالة",
    nameEn: "ACWA Power Salalah",
    marketId: "msm",
    sector: "Utilities",
    sectorAr: "مرافق",
    price: 0.068,
    change: -0.001,
    changePercent: -1.45,
    high: 0.07,
    low: 0.067,
    volume: 230000,
    marketCap: 190000000,
    currency: "OMR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "BKSB",
    nameAr: "بنك صحار الدولي",
    nameEn: "Sohar International Bank",
    marketId: "msm",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 0.118,
    change: 0.003,
    changePercent: 2.61,
    high: 0.12,
    low: 0.116,
    volume: 670000,
    marketCap: 410000000,
    currency: "OMR",
    halalStatus: "suspicious",
    halalReason: "halalReasons.conventionalBanking",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "OQEP",
    nameAr: "أوكيو للاستكشاف",
    nameEn: "OQ Exploration",
    marketId: "msm",
    sector: "Energy",
    sectorAr: "طاقة",
    price: 0.348,
    change: 0.015,
    changePercent: 4.5,
    high: 0.355,
    low: 0.335,
    volume: 1100000,
    marketCap: 1500000000,
    currency: "OMR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
];

// ── Saudi Exchange (Tadawul) ──

export const TADAWUL_STOCKS: LocalStock[] = [
  {
    symbol: "2222",
    nameAr: "أرامكو السعودية",
    nameEn: "Saudi Aramco",
    marketId: "tadawul",
    sector: "Energy",
    sectorAr: "طاقة",
    price: 28.65,
    change: -0.15,
    changePercent: -0.52,
    high: 28.9,
    low: 28.5,
    volume: 12500000,
    marketCap: 6900000000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "1180",
    nameAr: "الأهلي السعودي",
    nameEn: "SNB",
    marketId: "tadawul",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 35.7,
    change: 0.25,
    changePercent: 0.71,
    high: 35.9,
    low: 35.45,
    volume: 3200000,
    marketCap: 178500000000,
    currency: "SAR",
    halalStatus: "suspicious",
    halalReason: "halalReasons.conventionalBanking",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "2010",
    nameAr: "سابك",
    nameEn: "SABIC",
    marketId: "tadawul",
    sector: "Petrochemicals",
    sectorAr: "بتروكيماويات",
    price: 72.8,
    change: 1.2,
    changePercent: 1.68,
    high: 73.5,
    low: 71.6,
    volume: 2800000,
    marketCap: 218400000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "7010",
    nameAr: "STC",
    nameEn: "STC",
    marketId: "tadawul",
    sector: "Telecom",
    sectorAr: "اتصالات",
    price: 41.15,
    change: 0.35,
    changePercent: 0.86,
    high: 41.5,
    low: 40.8,
    volume: 4100000,
    marketCap: 205750000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "2082",
    nameAr: "أكوا باور",
    nameEn: "ACWA Power",
    marketId: "tadawul",
    sector: "Utilities",
    sectorAr: "مرافق",
    price: 310.0,
    change: -4.0,
    changePercent: -1.27,
    high: 315.0,
    low: 308.0,
    volume: 1500000,
    marketCap: 210000000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "1120",
    nameAr: "الراجحي",
    nameEn: "Al Rajhi Bank",
    marketId: "tadawul",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 93.5,
    change: 0.8,
    changePercent: 0.86,
    high: 94.0,
    low: 92.7,
    volume: 5600000,
    marketCap: 234000000000,
    currency: "SAR",
    halalStatus: "halal",
    halalReason: "halalReasons.islamicBank",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "2350",
    nameAr: "كيان السعودية",
    nameEn: "Saudi Kayan",
    marketId: "tadawul",
    sector: "Petrochemicals",
    sectorAr: "بتروكيماويات",
    price: 12.98,
    change: -0.22,
    changePercent: -1.67,
    high: 13.3,
    low: 12.8,
    volume: 7800000,
    marketCap: 48675000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "4200",
    nameAr: "الدريس",
    nameEn: "Aldrees",
    marketId: "tadawul",
    sector: "Retail",
    sectorAr: "تجزئة",
    price: 78.2,
    change: 1.5,
    changePercent: 1.95,
    high: 79.0,
    low: 77.0,
    volume: 890000,
    marketCap: 31280000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "4001",
    nameAr: "عبدالله العثيم",
    nameEn: "Abdullah Al Othaim",
    marketId: "tadawul",
    sector: "Retail",
    sectorAr: "تجزئة",
    price: 45.6,
    change: 0.4,
    changePercent: 0.88,
    high: 46.0,
    low: 45.2,
    volume: 1200000,
    marketCap: 22800000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "4030",
    nameAr: "البحر الأحمر",
    nameEn: "Red Sea International",
    marketId: "tadawul",
    sector: "Real Estate",
    sectorAr: "عقارات",
    price: 52.3,
    change: -0.7,
    changePercent: -1.32,
    high: 53.5,
    low: 51.8,
    volume: 650000,
    marketCap: 15690000000,
    currency: "SAR",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
];

// ── Dubai Financial Market (DFM) ──

export const DFM_STOCKS: LocalStock[] = [
  {
    symbol: "EMAAR",
    nameAr: "إعمار العقارية",
    nameEn: "Emaar Properties",
    marketId: "dfm",
    sector: "Real Estate",
    sectorAr: "عقارات",
    price: 9.35,
    change: 0.15,
    changePercent: 1.63,
    high: 9.45,
    low: 9.2,
    volume: 18000000,
    marketCap: 82280000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "DIB",
    nameAr: "بنك دبي الإسلامي",
    nameEn: "Dubai Islamic Bank",
    marketId: "dfm",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 6.12,
    change: 0.08,
    changePercent: 1.32,
    high: 6.2,
    low: 6.05,
    volume: 8500000,
    marketCap: 44100000000,
    currency: "AED",
    halalStatus: "halal",
    halalReason: "halalReasons.islamicBank",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "DU",
    nameAr: "دو",
    nameEn: "Du (EITC)",
    marketId: "dfm",
    sector: "Telecom",
    sectorAr: "اتصالات",
    price: 6.85,
    change: -0.05,
    changePercent: -0.72,
    high: 6.95,
    low: 6.8,
    volume: 3200000,
    marketCap: 31600000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "DEWA",
    nameAr: "هيئة كهرباء ومياه دبي",
    nameEn: "DEWA",
    marketId: "dfm",
    sector: "Utilities",
    sectorAr: "مرافق",
    price: 2.68,
    change: 0.02,
    changePercent: 0.75,
    high: 2.72,
    low: 2.65,
    volume: 25000000,
    marketCap: 134000000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "SALIK",
    nameAr: "سالك",
    nameEn: "Salik",
    marketId: "dfm",
    sector: "Services",
    sectorAr: "خدمات",
    price: 4.15,
    change: 0.1,
    changePercent: 2.47,
    high: 4.2,
    low: 4.05,
    volume: 9800000,
    marketCap: 31000000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "ENBD",
    nameAr: "الإمارات دبي الوطني",
    nameEn: "Emirates NBD",
    marketId: "dfm",
    sector: "Banking",
    sectorAr: "بنوك",
    price: 18.9,
    change: -0.3,
    changePercent: -1.56,
    high: 19.3,
    low: 18.75,
    volume: 4500000,
    marketCap: 118000000000,
    currency: "AED",
    halalStatus: "non_compliant",
    halalReason: "halalReasons.interestBased",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "DAMAC",
    nameAr: "داماك العقارية",
    nameEn: "DAMAC Properties",
    marketId: "dfm",
    sector: "Real Estate",
    sectorAr: "عقارات",
    price: 7.42,
    change: 0.28,
    changePercent: 3.92,
    high: 7.5,
    low: 7.15,
    volume: 14000000,
    marketCap: 44520000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "PARKIN",
    nameAr: "باركن",
    nameEn: "Parkin",
    marketId: "dfm",
    sector: "Services",
    sectorAr: "خدمات",
    price: 3.78,
    change: 0.05,
    changePercent: 1.34,
    high: 3.82,
    low: 3.72,
    volume: 7200000,
    marketCap: 28000000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "TECOM",
    nameAr: "تيكوم",
    nameEn: "TECOM Group",
    marketId: "dfm",
    sector: "Real Estate",
    sectorAr: "عقارات",
    price: 5.2,
    change: -0.08,
    changePercent: -1.52,
    high: 5.32,
    low: 5.15,
    volume: 5100000,
    marketCap: 26000000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "ARMX",
    nameAr: "أرامكس",
    nameEn: "Aramex",
    marketId: "dfm",
    sector: "Logistics",
    sectorAr: "لوجستي",
    price: 2.35,
    change: 0.03,
    changePercent: 1.29,
    high: 2.38,
    low: 2.32,
    volume: 6800000,
    marketCap: 11500000000,
    currency: "AED",
    halalStatus: "halal",
    lastUpdated: new Date().toISOString(),
  },
];

// ── Sukuk ──

export const SUKUK_LIST: Sukuk[] = [
  {
    id: "sukuk-1",
    nameAr: "صكوك حكومة عمان 2028",
    nameEn: "Oman Sovereign Sukuk 2028",
    issuer: "Government of Oman",
    issuerAr: "حكومة سلطنة عمان",
    marketId: "msm",
    yieldPercent: 5.25,
    maturityDate: "2028-06-15",
    faceValue: 1000,
    currentPrice: 1015.5,
    currency: "OMR",
    rating: "BB+",
    halalStatus: "halal",
  },
  {
    id: "sukuk-2",
    nameAr: "صكوك أرامكو 2030",
    nameEn: "Aramco Sukuk 2030",
    issuer: "Saudi Aramco",
    issuerAr: "أرامكو السعودية",
    marketId: "tadawul",
    yieldPercent: 4.8,
    maturityDate: "2030-03-20",
    faceValue: 1000,
    currentPrice: 1008.25,
    currency: "SAR",
    rating: "A+",
    halalStatus: "halal",
  },
  {
    id: "sukuk-3",
    nameAr: "صكوك الإمارات 2027",
    nameEn: "UAE Sovereign Sukuk 2027",
    issuer: "UAE Government",
    issuerAr: "حكومة الإمارات",
    marketId: "dfm",
    yieldPercent: 4.15,
    maturityDate: "2027-09-10",
    faceValue: 1000,
    currentPrice: 1022.0,
    currency: "AED",
    rating: "AA",
    halalStatus: "halal",
  },
  {
    id: "sukuk-4",
    nameAr: "صكوك بنك مسقط الإسلامي",
    nameEn: "Meethaq Sukuk",
    issuer: "Bank Muscat Meethaq",
    issuerAr: "بنك مسقط ميثاق",
    marketId: "msm",
    yieldPercent: 5.75,
    maturityDate: "2029-01-15",
    faceValue: 100,
    currentPrice: 102.3,
    currency: "OMR",
    rating: "BBB+",
    halalStatus: "halal",
  },
  {
    id: "sukuk-5",
    nameAr: "صكوك دار الأركان",
    nameEn: "Dar Al Arkan Sukuk",
    issuer: "Dar Al Arkan",
    issuerAr: "دار الأركان",
    marketId: "tadawul",
    yieldPercent: 6.5,
    maturityDate: "2031-07-01",
    faceValue: 1000,
    currentPrice: 985.0,
    currency: "SAR",
    rating: "BB",
    halalStatus: "halal",
  },
  {
    id: "sukuk-6",
    nameAr: "صكوك إعمار 2029",
    nameEn: "Emaar Sukuk 2029",
    issuer: "Emaar Properties",
    issuerAr: "إعمار العقارية",
    marketId: "dfm",
    yieldPercent: 5.1,
    maturityDate: "2029-11-30",
    faceValue: 1000,
    currentPrice: 1012.0,
    currency: "AED",
    rating: "BBB",
    halalStatus: "halal",
  },
];

// ── Investment Funds ──

export const FUNDS_LIST: InvestmentFund[] = [
  {
    id: "fund-1",
    nameAr: "صندوق الاستثمار العماني",
    nameEn: "Oman Investment Fund",
    managerAr: "بنك مسقط لإدارة الأصول",
    managerEn: "BankMuscat Asset Management",
    marketId: "msm",
    nav: 1.245,
    navChange: 0.008,
    navChangePercent: 0.65,
    ytdReturn: 8.3,
    expenseRatio: 1.5,
    currency: "OMR",
    category: "Equity",
    categoryAr: "أسهم",
    halalStatus: "suspicious",
  },
  {
    id: "fund-2",
    nameAr: "صندوق الرائد الإسلامي",
    nameEn: "Al Raed Islamic Fund",
    managerAr: "الراجحي المالية",
    managerEn: "Al Rajhi Capital",
    marketId: "tadawul",
    nav: 56.32,
    navChange: 0.45,
    navChangePercent: 0.81,
    ytdReturn: 12.5,
    expenseRatio: 1.2,
    currency: "SAR",
    category: "Islamic Equity",
    categoryAr: "أسهم إسلامية",
    halalStatus: "halal",
  },
  {
    id: "fund-3",
    nameAr: "صندوق الإمارات للصكوك",
    nameEn: "Emirates Sukuk Fund",
    managerAr: "الإمارات لإدارة الأصول",
    managerEn: "Emirates Asset Management",
    marketId: "dfm",
    nav: 12.78,
    navChange: 0.03,
    navChangePercent: 0.24,
    ytdReturn: 5.8,
    expenseRatio: 0.85,
    currency: "AED",
    category: "Sukuk",
    categoryAr: "صكوك",
    halalStatus: "halal",
  },
  {
    id: "fund-4",
    nameAr: "صندوق الأهلي متعدد الأصول",
    nameEn: "SNB Multi-Asset Fund",
    managerAr: "الأهلي المالية",
    managerEn: "SNB Capital",
    marketId: "tadawul",
    nav: 23.1,
    navChange: -0.12,
    navChangePercent: -0.52,
    ytdReturn: 7.1,
    expenseRatio: 1.75,
    currency: "SAR",
    category: "Multi-Asset",
    categoryAr: "متعدد الأصول",
    halalStatus: "halal",
  },
  {
    id: "fund-5",
    nameAr: "صندوق عمان للدخل الثابت",
    nameEn: "Oman Fixed Income Fund",
    managerAr: "عمان للاستثمار",
    managerEn: "Oman Investment",
    marketId: "msm",
    nav: 0.982,
    navChange: 0.001,
    navChangePercent: 0.1,
    ytdReturn: 4.2,
    expenseRatio: 0.95,
    currency: "OMR",
    category: "Fixed Income",
    categoryAr: "دخل ثابت",
    halalStatus: "suspicious",
  },
  {
    id: "fund-6",
    nameAr: "صندوق دبي الإسلامي للأسهم",
    nameEn: "DIB Islamic Equity Fund",
    managerAr: "بنك دبي الإسلامي",
    managerEn: "DIB Asset Management",
    marketId: "dfm",
    nav: 8.95,
    navChange: 0.12,
    navChangePercent: 1.36,
    ytdReturn: 11.2,
    expenseRatio: 1.1,
    currency: "AED",
    category: "Islamic Equity",
    categoryAr: "أسهم إسلامية",
    halalStatus: "halal",
  },
];

// ── Helper ──

export function getAllStocks(): LocalStock[] {
  return [...MSM_STOCKS, ...TADAWUL_STOCKS, ...DFM_STOCKS];
}

export function getStocksByMarket(marketId: MarketId): LocalStock[] {
  switch (marketId) {
    case "msm":
      return MSM_STOCKS;
    case "tadawul":
      return TADAWUL_STOCKS;
    case "dfm":
      return DFM_STOCKS;
    default:
      return [];
  }
}

export function getSukukByMarket(marketId?: MarketId): Sukuk[] {
  if (!marketId) return SUKUK_LIST;
  return SUKUK_LIST.filter((s) => s.marketId === marketId);
}

export function getFundsByMarket(marketId?: MarketId): InvestmentFund[] {
  if (!marketId) return FUNDS_LIST;
  return FUNDS_LIST.filter((f) => f.marketId === marketId);
}
